services:
  postgres: 
    image: 'bitnami/postgresql:latest'
    container_name: fandoh
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: webfandoh
    volumes:
      - './data/pg:/data/postgres'
